#######################################################################################
#    ███    ██  █████  ████████       ███    ███  ██████  ████████ ██████             #
#    ████   ██ ██   ██    ██          ████  ████ ██    ██    ██    ██   ██            #
#    ██ ██  ██ ███████    ██    █████ ██ ████ ██ ██    ██    ██    ██   ██            #
#    ██  ██ ██ ██   ██    ██          ██  ██  ██ ██    ██    ██    ██   ██            #
#    ██   ████ ██   ██    ██          ██      ██  ██████     ██    ██████             #
#######################################################################################
# Made by Nat0uille & Love                                                            #
# Config version : 1.1                                                                #
#######################################################################################
# All texts use the MiniMessage format. If you use anything else, it will not work!!! #
# To create your messages, you can use the website https://webui.advntr.dev/          #
#######################################################################################
# SETTINGS                                                                            #
#######################################################################################
motd:
  # Displays the selected motd
  selected: 1
  1:
    line1:
      text: "<bold><gradient:#C70000:#951919>NAT-MOTD</gradient></bold>"
      center: true
    line2:
      text: "<#cfcfcf>ᴅᴇꜰᴀᴜʟᴛ ᴄᴏɴꜰɪɢ (ᴄᴏɴꜰɪɢ.ʏᴍʟ)"
      center: false
    players-max: 0
  2:
    line1:
      text: "<bold><gradient:#C70000:#951919>NAT-MOTD</gradient></bold>"
      center: false
    line2:
      text: "<#cfcfcf>ᴅᴇꜰᴀᴜʟᴛ ᴄᴏɴꜰɪɢ (ᴄᴏɴꜰɪɢ.ʏᴍʟ)"
      center: true
    players-max: 9999


#######################################################################################
# MESSAGES                                                                            #
#######################################################################################
messages:
  # plugin prefix
  prefix: "<bold><gradient:#C70000:#951919>NAT-MOTD</gradient></bold> <gray>-"
  # message displayed when a player does not have permission
  nopermission: "<#C70000><bold>✖</bold> You do not have permission to execute this command. "
  # message displayed when /nat-motd
  usage: "<#ffc369><bold>USAGE</bold>\n/nat-motd reload: ʀᴇʟᴏᴀᴅ ʟᴇ ᴍᴏᴛᴅ.\n/nat-motd select <number>: ѕᴇʟᴇᴄᴛ ᴍᴏᴛᴅ"
  # message displayed when /nat-motd select with no number
  usage-select: "<#ffc369><bold>USAGE</bold>: /nat-motd select <number>"
  # message displayed when /nat-motd reload is use
  reload: "<#C70000><bold>✔</bold> The MOTD has been reloaded successfully!"
  # message displayed when /nat-motd select is use
  select: "<#C70000><bold>✔</bold> You have selected the MOTD {number}."
  # message displayed when the plugin is outdated
  outdated: "<#C70000>The plugin is not up to date. Local version: <bold>{local}</bold>, latest version: <bold>{latest}</bold>"