name: Nat-MOTD
version: '1.0-ALPHA'
main: fr.Nat0uille.NatMOTD.Main
api-version: '1.21'
load: STARTUP
authors: [ Nat0uille ]
commands:
    nat-motd:
        description: "Commandes de gestion du MOTD"
        usage: "/Nat-MOTD reload"
permission:
  NatMOTD.reload:
    description: "Permission pour recharger le MOTD"
    default: op