name: Nat-MOTD
version: '1.0'
main: fr.Nat0uille.NatMOTD.Main
api-version: '1.21'
load: STARTUP
authors: [ Nat0uille ]
commands:
    nat-motd:
      aliases: [ motd ]
permission:
  natmotd.reload:
    default: op
  natmotd.select:
    default: op
  natmotd.admin:
    default: op
    children:
      natmotd.reload: true
      natmotd.select: true
  natmotd.*:
    default: op
    children:
      natmotd.admin: true